Reactivated workflows
spn regression added to no-mpi-spn workflow

diff --git a/Make/MkRules b/Make/MkRules
--- a/Make/MkRules
+++ b/Make/MkRules
@@ -222,7 +222,7 @@ $(foreach prog,$(EXES),$(eval $(call LINK_template,$(prog))))
 define RUNTEST_template
 echo -n "$(_col_test)["$(1)"]$(_col_norm) ..." ; rm -f debug out_0 err_0 ; \
 export OMPI_MCA_btl_base_warn_component_unused=0 ;\
-$(RUNTEST) ./$(1) -i $(1).in >/dev/null && echo " $(_cpassed)" || ( echo " $(_cfailed)" && touch .test_failed && tail -n 80 out_0 ); 
+$(RUNTEST) ./$(1) -i $(1).in >/dev/null && echo " $(_cpassed)" || ( echo " $(_cfailed)" && touch .test_failed && tail -n 80 out_0 && cp out_0 $(1).out );
 endef
 
 runtests:
